// 자동 생성 파일 — 직접 수정 금지. `node scripts/genStickerManifest.cjs` 로 재생성.
// deco 테마형 일러스트를 주제별 servable 이름(stk-*)으로 정리한 결과.
export const STICKER_MANIFEST: Record<string, string[]> = {
  "autumn": [
    "/assets/deco/stk-autumn-1.png",
    "/assets/deco/stk-autumn-2.png",
    "/assets/deco/stk-autumn-3.png",
    "/assets/deco/stk-autumn-4.png",
    "/assets/deco/stk-autumn-5.png"
  ],
  "chuseok": [
    "/assets/deco/stk-chuseok-1.png",
    "/assets/deco/stk-chuseok-2.png",
    "/assets/deco/stk-chuseok-3.png",
    "/assets/deco/stk-chuseok-4.png",
    "/assets/deco/stk-chuseok-5.png"
  ],
  "dino": [
    "/assets/deco/stk-dino-1.png",
    "/assets/deco/stk-dino-2.png",
    "/assets/deco/stk-dino-3.png",
    "/assets/deco/stk-dino-4.png",
    "/assets/deco/stk-dino-5.png",
    "/assets/deco/stk-dino-6.png",
    "/assets/deco/stk-dino-7.png",
    "/assets/deco/stk-dino-8.png"
  ],
  "mart": [
    "/assets/deco/stk-mart-1.png",
    "/assets/deco/stk-mart-2.png",
    "/assets/deco/stk-mart-3.png",
    "/assets/deco/stk-mart-4.png"
  ],
  "media": [
    "/assets/deco/stk-media-1.png",
    "/assets/deco/stk-media-2.png",
    "/assets/deco/stk-media-3.png",
    "/assets/deco/stk-media-4.png",
    "/assets/deco/stk-media-5.png",
    "/assets/deco/stk-media-6.png",
    "/assets/deco/stk-media-7.png"
  ],
  "shapes": [
    "/assets/deco/stk-shapes-1.png",
    "/assets/deco/stk-shapes-2.png",
    "/assets/deco/stk-shapes-3.png",
    "/assets/deco/stk-shapes-4.png",
    "/assets/deco/stk-shapes-5.png",
    "/assets/deco/stk-shapes-6.png",
    "/assets/deco/stk-shapes-7.png"
  ],
  "summer": [
    "/assets/deco/stk-summer-1.png",
    "/assets/deco/stk-summer-2.png",
    "/assets/deco/stk-summer-3.png",
    "/assets/deco/stk-summer-4.png",
    "/assets/deco/stk-summer-5.png",
    "/assets/deco/stk-summer-6.png",
    "/assets/deco/stk-summer-7.png",
    "/assets/deco/stk-summer-8.png",
    "/assets/deco/stk-summer-9.png",
    "/assets/deco/stk-summer-10.png",
    "/assets/deco/stk-summer-11.png",
    "/assets/deco/stk-summer-12.png",
    "/assets/deco/stk-summer-13.png",
    "/assets/deco/stk-summer-14.png",
    "/assets/deco/stk-summer-15.png",
    "/assets/deco/stk-summer-16.png",
    "/assets/deco/stk-summer-17.png",
    "/assets/deco/stk-summer-18.png",
    "/assets/deco/stk-summer-19.png",
    "/assets/deco/stk-summer-20.png",
    "/assets/deco/stk-summer-21.png",
    "/assets/deco/stk-summer-22.png",
    "/assets/deco/stk-summer-23.png",
    "/assets/deco/stk-summer-24.png",
    "/assets/deco/stk-summer-25.png",
    "/assets/deco/stk-summer-26.png",
    "/assets/deco/stk-summer-27.png",
    "/assets/deco/stk-summer-28.png",
    "/assets/deco/stk-summer-29.png",
    "/assets/deco/stk-summer-30.png",
    "/assets/deco/stk-summer-31.png",
    "/assets/deco/stk-summer-32.png",
    "/assets/deco/stk-summer-33.png",
    "/assets/deco/stk-summer-34.png",
    "/assets/deco/stk-summer-35.png",
    "/assets/deco/stk-summer-36.png"
  ],
  "traffic": [
    "/assets/deco/stk-traffic-1.png",
    "/assets/deco/stk-traffic-2.png",
    "/assets/deco/stk-traffic-3.png",
    "/assets/deco/stk-traffic-4.png",
    "/assets/deco/stk-traffic-5.png",
    "/assets/deco/stk-traffic-6.png",
    "/assets/deco/stk-traffic-7.png",
    "/assets/deco/stk-traffic-8.png",
    "/assets/deco/stk-traffic-9.png",
    "/assets/deco/stk-traffic-10.png",
    "/assets/deco/stk-traffic-11.png",
    "/assets/deco/stk-traffic-12.png",
    "/assets/deco/stk-traffic-13.png",
    "/assets/deco/stk-traffic-14.png",
    "/assets/deco/stk-traffic-15.png",
    "/assets/deco/stk-traffic-16.png",
    "/assets/deco/stk-traffic-17.png",
    "/assets/deco/stk-traffic-18.png",
    "/assets/deco/stk-traffic-19.png"
  ],
  "winter": [
    "/assets/deco/stk-winter-1.png",
    "/assets/deco/stk-winter-2.png",
    "/assets/deco/stk-winter-3.png",
    "/assets/deco/stk-winter-4.png",
    "/assets/deco/stk-winter-5.png",
    "/assets/deco/stk-winter-6.png",
    "/assets/deco/stk-winter-7.png",
    "/assets/deco/stk-winter-8.png",
    "/assets/deco/stk-winter-9.png",
    "/assets/deco/stk-winter-10.png",
    "/assets/deco/stk-winter-11.png",
    "/assets/deco/stk-winter-12.png",
    "/assets/deco/stk-winter-13.png",
    "/assets/deco/stk-winter-14.png",
    "/assets/deco/stk-winter-15.png"
  ]
};
